import {
  AlertTriangle,
  Bell,
  Bot,
  CalendarClock,
  Camera,
  CheckCircle2,
  ClipboardList,
  Clock,
  Cog,
  Filter,
  Flag,
  GitBranch,
  Headset,
  Mail,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Package,
  Pause,
  Plug,
  Plus,
  RefreshCw,
  Send,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Split,
  StickyNote,
  Store,
  Tag,
  Target,
  ThumbsUp,
  UserPlus,
  Users,
  Webhook,
  Workflow,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  bolt: Zap,
  robot: Bot,
  plug: Plug,
  flow: Workflow,
  send: Send,
  chat: Headset,
  clock: Clock,
  spark: Sparkles,
  check: CheckCircle2,
  warn: AlertTriangle,
  filter: Filter,
  plus: Plus,
  branch: GitBranch,
  target: Target,
  cart: ShoppingCart,
  tag: Tag,
  shield: Shield,
  head: Headset,
  refresh: RefreshCw,
  mail: Mail,
  pause: Pause,
  cog: Cog,
  whatsapp: MessageCircle,
  megaphone: Megaphone,
  instagram: Camera,
  facebook: ThumbsUp,
  shopify: ShoppingBag,
  webhook: Webhook,
  userPlus: UserPlus,
  form: ClipboardList,
  woo: Store,
  package: Package,
  calendar: CalendarClock,
  message: MessageSquare,
  users: Users,
  flag: Flag,
  note: StickyNote,
  bell: Bell,
  split: Split,
}

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? Cog
}
